### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#701] opened 2022-05-03 13:02 UTC
The current develop branch has a failing test:

```
DatasetJsonParserTest.savePlatyView:104->validateJSON:80 ? Validation #/views/...
```

Could you please have a look @K-Meech ?

**Comment by constantinpape** [comment] 2022-05-03 22:39
@K-Meech could you make a MoBIE-beta release once you have fixed this, since this should fix #693 (which is very annoying) and #695 (which we need for the paper figures). Thanks!

**Comment by K-Meech** [comment] 2022-05-04 07:02
Yes - I can do that this afternoon

**Comment by K-Meech** [comment] 2022-05-04 07:22
@constantinpape - I can't open the platybrowser with the current MoBIE-beta. Is something wrong with the S3?
```
Error opening: https://raw.githubusercontent.com/mobie/platybrowser-project/main/data/1.0.1/images/remote/sbem-6dpf-1-whole-raw.xml
com.amazonaws.services.s3.model.AmazonS3Exception: Service Unavailable (Service: Amazon S3; Status Code: 503; Error Code: 503 Service Unavailable; Request ID: null; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1811)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1395)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1371)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5062)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5008)
	at com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1416)
	at org.embl.mobie.io.util.S3Utils.getS3Client(S3Utils.java:69)
	at org.embl.mobie.io.n5.loaders.N5S3ImageLoader$N5AmazonS3ReaderCreator.create(N5S3ImageLoader.java:81)
	at org.embl.mobie.io.n5.loaders.N5S3ImageLoader.<init>(N5S3ImageLoader.java:55)
	at org.embl.mobie.io.n5.openers.N5S3Opener.readURLData(N5S3Opener.java:129)
	at org.embl.mobie.io.n5.openers.N5S3Opener.readURL(N5S3Opener.java:42)
	at org.embl.mobie.io.SpimDataOpener.openBdvN5S3(SpimDataOpener.java:113)
	at org.embl.mobie.io.SpimDataOpener.openSpimData(SpimDataOpener.java:70)
	at org.embl.mobie.viewer.MoBIE.tryOpenSpimData(MoBIE.java:423)
	at org.embl.mobie.viewer.MoBIE.openSourceAndConverter(MoBIE.java:393)
	at org.embl.mobie.viewer.MoBIE.lambda$openSourceAndConverters$0(MoBIE.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by constantinpape** [comment] 2022-05-04 07:25
Yes, seems like it's down. I have written to Josep about it.

**Comment by K-Meech** [comment] 2022-05-04 07:28
Ok - thanks! This might be the cause of the test failure then - as it needs to open the platybrowser.

**Comment by constantinpape** [comment] 2022-05-04 07:31
> This might be the cause of the test failure then - as it needs to open the platybrowser.

I am not sure, since I could still access the EMBL S3 yesterday evening. And everything is down now, not only the platybrowser.
But we'll see once it's back up.

**Comment by constantinpape** [comment] 2022-05-04 07:47
@K-Meech EMBL s3 is working again.

**Comment by K-Meech** [comment] 2022-05-04 07:59
Thanks @constantinpape . Just checked - and you're right - there is some other issue that is making the test fail. I'll look into it.

**Comment by K-Meech** [comment] 2022-05-04 08:11
@constantinpape - it seems to be because the ```blendingMode``` is being written for segmentations. Is it right that this should only be written to views for images?

**Comment by constantinpape** [comment] 2022-05-04 08:14
@K-Meech yes, we recently changed this and removed `blendingMode` from the `segmentationDisplay` since there is only one sensible option for it. I thought we are not using it in any of the projects, but apparently we do in the platybrowser. I will fix it and ping you again.

**Comment by K-Meech** [comment] 2022-05-04 08:17
I don't think it's being used in the project - it's being saved wrongly when 'save current view...' is used. I can fix it.

**Comment by constantinpape** [comment] 2022-05-04 08:19
I see. Yes, if you remove it then everything should work again.

**Comment by K-Meech** [comment] 2022-05-04 11:57
This is fixed on the current develop branch + I made a new MoBIE-beta release

**Closed by K-Meech** 2022-05-04 11:57 UTC

**Comment by constantinpape** [comment] 2022-05-04 14:47
Thanks @K-Meech. I will check out the new MoBIE beta later today.
