### ISSUE TITLE
Improve bookmark position and transform

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#114] opened 2020-09-10 11:56 UTC
We are having the issue that our Bookmarks do not generate a perfect view if users have the BDV window sized to a different size compared to the user that recorded the view. For example the appearance of the figures of the PlatyBrowser publication depends quite a bit (too much) on the window size, which we do not (and should not) control.

I was thinking that maybe we could get the physical coordinates of the 4 corner points that lie in the largest enclosed square of the BDV window where the bookmark is recorded (the reason for choosing the smallest fully enclosed square is that the BDV window may be non-square and have different aspect ratios for different users). 

Then, if a user revokes the bookmark, MoBIE would compute an `AffineTransform` (i.e., the `ViewerTransform`) such that those 4 point again come to lie in the corners of the largest enclosed square of the current BDV window. If the BDV window would be squared this would 100% generate the same view, if there are different aspect ratios it would at least show something quite similar, I think...

I guess 3 of the 4 corner coordinates would be sufficient to fully specify everything, but maybe it is easier to record all 4, because it seems arbitrary which one to leave out?!

@constantinpape 
@K-Meech 
@vzinche 
1. What do you think? Other ideas?
1. Does someone have code (or can outline a recipe) for generating an AffineTransform that projects 4 coordinates (the physical coordinates stored in the bookmark) onto 4 other coordinates (the coordinates of the smallest fully enclosed square within the ViewerWindow)?

**Comment by constantinpape** [comment] 2020-09-10 14:03
@tischi I think that sounds very reasonable overall.

> I guess 3 of the 4 corner coordinates would be sufficient to fully specify everything, but maybe it is easier to record all 4, because it seems arbitrary which one to leave out?!

If we assume it's square, wouldn't 2 corners suffice? I think the "lower left" and "top right" corner should be enough, no?

**Comment by K-Meech** [comment] 2020-09-10 14:30
Sounds good to me! And I agree that the two corners would suffice, but I guess it's easy to record all four anyway...

As for how to map the coordinates, I'm not sure. Would something like this work?
Deal with the translation:
-Translate the view centre so centre of largest square in viewer == centre largest square from bookmark

Deal with rotation:
-level view so normals and orientation the same - something like: https://github.com/K-Meech/crosshair/blob/master/src/main/java/de/embl/schwab/crosshair/utils/GeometryUtils.java#L463. 

Deal with zoom:
-calculate a zoom factor as the length of the edge of the square of the viewer / length of the edge of the bookmark square (in viewer coordinates)
-apply this zoom somehow? (I'm not sure how this works with bdv...)

**Comment by constantinpape** [comment] 2020-09-10 15:14
I think we can make use of the BDV transformation that we get already.
So you might not have to compute the rotation and maybe the following would work:

- Apply the BDV transformation and position (as we have them in the bookmarks already).
- Compare the corners of the viewer that you get after this transformation to the corners that were saved. 
- If I understand what is happening in BDV correctly, you should now be able to map to the saved corners by just applying a scale / zoom.

**Comment by tischi** [comment] 2020-09-10 15:24
Just got good advice from Tobias (see here: https://gitter.im/bigdataviewer/bigdataviewer-core):

> ...then basically when you make a bookmark:
> pre-concatenate a transform that takes the window center to (0,0)
> pre-concatenate a transform that scales by 1/window-width
> store that
> when you retrieve the bookmark
> invert those operations
> (with possibly different window center and width)

So we store a normalised (with respect to window-width) and centred `ViewerTransform`.
The other options would have worked, too, but that one is easier to implement, I think.

**Comment by vzinche** [comment] 2020-09-10 16:20
Personally, I often felt the need to move to a specific position/view, but never to a norm view. I would say it's fine to leave this functionality for the bookmarks only

**Comment by K-Meech** [comment] 2020-09-10 16:27
Moving it to the right click menu sounds like a good plan. Otherwise, maybe you could have a drop down menu to select position / view/norm view to the left of where you type? Then you only need one line for all 3 options.

**Comment by tischi** [comment] 2020-09-11 05:05
I am now thinking that moving to some interesting location that a collaborator found may in fact be one of the key features of MoBIE, so it probably should be in the main UI and not in the context menu.

So what about distinguishing views from normalised views by something like this?

`1,0,0,0,0,1,0,0,0,0,1,0` and `n1,n0,n0,n0,n0,n1,n0,n0,n0,n0,n1,n0`

If the user would click `Log current location` it would output

```
Position:
1,1,1
View:
1,0,0,0,0,1,0,0,0,0,1,0
View normalised to window size:
n1,n0,n0,n0,n0,n1,n0,n0,n0,n0,n1,n0
```

Then it would be easy to copy and paste, e.g., the last line into an e-mail and send to a collaborator who could just paste it into MoBIE, where there would just be a single `location:  [  paste here           ]  [move]` option, like we had it before.

Opinions?
Other ideas?

**Comment by constantinpape** [comment] 2020-09-11 07:33
> Then it would be easy to copy and paste, e.g., the last line into an e-mail and send to a collaborator who could just paste it into MoBIE, where there would just be a single `location: [ paste here ] [move]` option, like we had it before.
> 
> Opinions?
> Other ideas?

I like that idea; and I agree that this is a pretty central feature so I wouldn't move it to the context menu.

I think that eventually we might retire the not normal "not normalized" views. They are not so useful for sharing positions, but let's see how it works out with the new normalized views first.

**Comment by tischi** [comment] 2020-09-11 08:00
@constantinpape 
I guess within the stored Bookmarks we would not have all the `n`s because we specify it via the tag?!
You think that's an issue that the logging and copy and pasting requires the `n` and in the Bookmarks we would not have them. I guess we also could have them in the Bookmarks....  I am not sure.

**Comment by constantinpape** [comment] 2020-09-11 08:08
> I guess within the stored Bookmarks we would not have all the `n`s because we specify it via the tag?!
> You think that's an issue that the logging and copy and pasting requires the `n` and in the Bookmarks we would not have them. I guess we also could have them in the Bookmarks.... I am not sure.

Maybe it's better if we keep it more similar and just keep a single tag 'view' in the bookmarks and have
```
{
 view = [1, 1, 1, ...]  # this is the normal "unnormalized view"
 view = [n1, n1, n1, ...]  # this is the normalized view
}
``` 
then people could directly copy and paste into the bookmarks.

**Comment by tischi** [comment] 2020-09-11 09:04
ok, this would mean however that we cannot have both a normalised and unnormalised view at the same time.
for the transition period and also for clarity (which would be redundant, but maybe that's fine) we could also do:

```
{
 view = [1, 1, 1, ...]  # this is the normal "unnormalized view"
 normView = [n1, n1, n1, ...]  # this is the normalized view
}
```

**Comment by constantinpape** [comment] 2020-09-11 09:09
Ok, let's go for it.

**Comment by constantinpape** [comment] 2020-09-15 14:54
@tischi 
I have added an example bookmark with a `normView` to this repo now:
https://github.com/mobie/covid-em-datasets

It cannot be read by MoBIE yet and fails with the following error:
```
ava.lang.NumberFormatException: For input string: "n0.03982960888406501"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at com.google.gson.stream.JsonReader.nextDouble(JsonReader.java:910)
	at com.google.gson.Gson$1.read(Gson.java:319)
	at com.google.gson.Gson$1.read(Gson.java:313)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at de.embl.cba.mobie.bookmark.BookmarksJsonParser.readBookmarksFromFile(BookmarksJsonParser.java:142)
	at de.embl.cba.mobie.bookmark.BookmarksJsonParser.parseBookmarks(BookmarksJsonParser.java:126)
	at de.embl.cba.mobie.bookmark.BookmarksJsonParser.readBookmarks(BookmarksJsonParser.java:105)
	at de.embl.cba.mobie.bookmark.BookmarksJsonParser.getBookmarks(BookmarksJsonParser.java:40)
	at de.embl.cba.mobie.ui.viewer.MoBIEViewer.fetchBookmarks(MoBIEViewer.java:197)
	at de.embl.cba.mobie.ui.viewer.MoBIEViewer.<init>(MoBIEViewer.java:87)
	at de.embl.cba.mobie.ui.viewer.MoBIEViewer.<init>(MoBIEViewer.java:59)
	at de.embl.cba.mobie.ui.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:18)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
It seems like the java parser expects a float and fails because it gets a string instead. `n0.0` etc. is not a valid float, so I need to store it as string to save it as a valid json; which means you need to load it as string to and then remove the `n` prefix and cast it to a float.

**Comment by tischi** [comment] 2020-09-15 15:42
The latest version on `MoBIE-beta` should work, could you try?

**Comment by constantinpape** [comment] 2020-09-15 16:29
Now the dataset loads, but when I try to load the bookmark I get the following error message:
```
Exception in thread "Thread-20" java.lang.NullPointerException
	at net.imglib2.realtransform.AffineTransform3D.set(AffineTransform3D.java:949)
	at de.embl.cba.mobie.utils.Utils.asAffineTransform3D(Utils.java:473)
	at de.embl.cba.mobie.bdv.BdvViewChanger.moveToLocation(BdvViewChanger.java:54)
	at de.embl.cba.mobie.bookmark.BookmarksManager.adaptViewerTransform(BookmarksManager.java:68)
	at de.embl.cba.mobie.bookmark.BookmarksManager.lambda$setView$0(BookmarksManager.java:37)
	at java.lang.Thread.run(Thread.java:748)
```
This is the bookmark at hand:
https://github.com/mobie/covid-em-datasets/blob/master/data/Covid19-S5-mock-Cell1-2/misc/bookmarks/default.json#L12-L25
I think it follows what we discussed [here](https://github.com/mobie/mobie-viewer-fiji/issues/114#issuecomment-690970775), so probably there is still something wrong with the parser?

To reproduce:
Select dataset `Covid19-S5-mock-cell1-2` and select the bookmark `test-normed-view`.

**Comment by tischi** [comment] 2020-09-16 07:54
Please update and try again.

**Comment by constantinpape** [comment] 2020-09-16 07:59
@tischi yes, the bookmark loads now.
@jhennies could you check that it actually shows what is intended?

**Closed** 2020-09-18 16:25 UTC
Labels: enhancement

**Comment by vzinche** [comment] 2020-09-23 08:52
@tischi a random request:
when you click on `Log Current Location` it shows you the position in brackets (). If you could remove them, it would be more copy-paste friendly, because the `location` field expects the position without brackets.
![Screenshot from 2020-09-23 10-51-36](https://user-images.githubusercontent.com/32451366/93989969-d7705980-fd8a-11ea-9ab3-784acfc5dfdf.png)
