### ISSUE TITLE
Project Creator trouble

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#639] opened 2022-03-08 13:01 UTC
Hi,

- Mac tested on 10.15.6 and 11.6
- new Fiji, MoBIE release
- Create/Edit MoBIE project
- add source
- bdv 
- link/move, click OK
- This should open a file browser to select the bdv xml
- instead all Fiji freezes

**Comment by martinschorb** [comment] 2022-03-08 13:20
Update:
all release versions we tried (Windows, Mac,...) refuse to load local projects created with the project creator.

**Comment by K-Meech** [comment] 2022-03-08 14:08
Thanks @martinschorb - do you see these issues with MoBIE-beta too? The main MoBIE release is quite far behind, so we might just need to do another release soon.

**Comment by K-Meech** [comment] 2022-03-08 14:28
Do you have the issue with opening local projects created with project creator too on MoBIE-beta? Or that's only on the release version?

For the file browsing, I can't reproduce this on Windows so it's a Mac specific issue. @tischi - would you have time to look into this with your mac? [This](https://github.com/mobie/mobie-viewer-fiji/blob/develop/src/main/java/org/embl/mobie/viewer/projectcreator/ui/ProjectsCreatorPanel.java#L614) line and [this](https://github.com/mobie/mobie-viewer-fiji/blob/develop/src/main/java/org/embl/mobie/viewer/projectcreator/ui/ProjectsCreatorPanel.java#L618) line are where the file browser should open for adding an n5 or ome-zarr image.

**Comment by tischi** [comment] 2022-03-10 17:09
I cannot reproduce this on my mac.

I created a new mobie project and then successfully opened it in three ways:
1. Within the Project Creator: View in MoBIE
2. Edit existing MoBIE project
3. Open MoBIE project

**Comment by constantinpape** [comment] 2022-03-10 17:12
@tischi: Did you use the latest MoBIE-beta version?

@martinschorb: Can you check if this issue still occurs with the latest MoBIE-beta? If yes, can you please make video to show how to exactly reproduce this?

**Comment by tischi** [comment] 2022-03-10 17:12
Ah, I see, it is about linking an existing image. I never did this. Also freezes for me. I will check.

**Comment by tischi** [comment] 2022-03-10 17:41
@K-Meech

If you google: JFileChooser hangs 
you find a lot.

Luckily I found some (non-obvious) fix in some other code of mine.
[Now it should work](https://github.com/mobie/mobie-viewer-fiji/commit/3f036f1e5724d43461a53f913f5d3072b6e8978a).
 
We'll probably have to add this also to the other places where we use the `JFileChooser`. @K-Meech do you think you could refactor your code such that it always uses below mechanism _without_ code duplication in this regard?

```
	       Runnable r = () -> {
			final JFileChooser jFileChooser = new JFileChooser( lastSelectedDir );
			jFileChooser.setFileFilter(new FileNameExtensionFilter( fileExtension, fileExtension ));
			path[ 0 ] = selectOpenPathFromFileSystem( objectName, jFileChooser );
			isDone.set( true );
		};
		SwingUtilities.invokeLater(r);
		while ( ! isDone.get() ){
			try {
				Thread.sleep( 100 );
			} catch ( InterruptedException e )
			{ e.printStackTrace(); }
		};
```

I think the best would be to have an own `class FileChooser`, which does all of this nonsense internally, and then we just call this class. This will enable us to replace this by something else once this bug (I think it is a bug in some Java versions) is fixed.

**Comment by K-Meech** [comment] 2022-03-11 08:08
Great - thanks @tischi!  I'll look through the code and make the rest of the ```JFileChooser``` calls use this too :)

**Comment by K-Meech** [comment] 2022-03-11 17:16
This should be fixed on the current develop branch

**Closed by K-Meech** 2022-03-11 17:16 UTC
Labels: project creator
