### ISSUE TITLE
mergedGrid as imageDisplay source in 3D

### ISSUE THREAD

**Issue by tibuch** [mobie/mobie-viewer-fiji#1004] opened 2023-03-17 08:29 UTC
Hi everyone,

Thanks for this great viewer! 

I am struggling to get the `mergedGrid` view working with 3D data. My understanding is that I can use `mergedGrid` to assemble different sources into a grid and then display the `mergedGrid`via `imageDisplay`:
```json
{
  "description": "A 3D projection mix example dataset.",
  "is2D": false,
  "sources": {
    "E07_C01_FITC_05": {
      "image": {
        "imageData": {
          "ome.zarr": {
            "channel": 0,
            "relativePath": "../../zarr-files/Projection-Mix.zarr/E/7/0"
          }
        }
      }
    },
    "E08_C01_FITC_05": {
      "image": {
        "imageData": {
          "ome.zarr": {
            "channel": 0,
            "relativePath": "../../zarr-files/Projection-Mix.zarr/E/8/0"
          }
        }
      }
    }
  },
  "views": {
    "default": {
      "isExclusive": true,
      "sourceDisplays": [
        {
          "imageDisplay": {
            "color": "r=115,g=255,b=0,a=255",
            "contrastLimits": [
              111,
              8065
            ],
            "name": "Plate-Channel-01",
            "opacity": 1.0,
            "sources": [
              "plate-channel-01-view"
            ]
          }
        }
      ],
      "sourceTransforms": [
        {
          "mergedGrid": {
            "mergedGridSourceName": "plate-channel-01-view",
            "positions": [
              [
                6,
                4
              ],
              [
                7,
                4
              ]
            ],
            "sources": [
              "E07_C01_FITC_05",
              "E08_C01_FITC_05"
            ]
          }
        }
      ],
      "uiSelectionGroup": "bookmarks"
    }
  }
}
```
This is what worked for me nicely with 2D data. Now that I try the same with 3D (ZYX) data I am only shown a single z-slice.
![broken-YZ-view](https://user-images.githubusercontent.com/5450869/225855313-05525cf2-cde5-41f2-a5a7-7dbe51fc603a.png)

When I change the `dataset.json` to:
```json
{
  "description": "A 3D projection mix example dataset.",
  "is2D": false,
  "sources": {
    "E07_C01_FITC_05": {
      "image": {
        "imageData": {
          "ome.zarr": {
            "channel": 0,
            "relativePath": "../../zarr-files/Projection-Mix.zarr/E/7/0"
          }
        }
      }
    },
    "E08_C01_FITC_05": {
      "image": {
        "imageData": {
          "ome.zarr": {
            "channel": 0,
            "relativePath": "../../zarr-files/Projection-Mix.zarr/E/8/0"
          }
        }
      }
    }
  },
  "views": {
    "default": {
      "isExclusive": true,
      "sourceDisplays": [
        {
          "imageDisplay": {
            "color": "r=115,g=255,b=0,a=255",
            "contrastLimits": [
              111,
              8065
            ],
            "name": "Plate-Channel-01",
            "opacity": 1.0,
            "sources": [
              "E07_C01_FITC_05",
              "E08_C01_FITC_05"
            ]
          }
        }
      ],
      "sourceTransforms": [
        {
          "mergedGrid": {
            "mergedGridSourceName": "plate-channel-01-view",
            "positions": [
              [
                6,
                4
              ],
              [
                7,
                4
              ]
            ],
            "sources": [
              "E07_C01_FITC_05",
              "E08_C01_FITC_05"
            ]
          }
        }
      ],
      "uiSelectionGroup": "bookmarks"
    }
  }
}
```
Where the individual sources are part of the `imageDisplay.sources` it is displayed as it should.
![working-YZ-view](https://user-images.githubusercontent.com/5450869/225854962-398ea0f4-4f41-4555-8f05-d89a74834039.png)

However, with the individual sources being part of the `imageDisplay` performance goes down quickly for increasing number of wells. I have a 384 well-plate and there it takes around 5min to initialize all the views. Once they are all loaded everything runs smoothly. But when I compare this performance to the `covid-example` where you use `mergedGrid` as outlined at the top, loading is super quick with many more sources. 

What might be the issue:
* I did something wrong writing the `dataset.json`.
* `mergedGrid`ignores the Z-dimension in the Fiji-viewer. If you could point me to the relevant code in the fiji-viewer I could try to take a look.

**Comment by tischi** [comment] 2023-03-17 08:45
@tibuch 

for just a couple of sources:

1. could you please try out `transformedGrid` instead of `mergedGrid`
2. could you share a minimal MoBIE project with me to reproduce this? it could be that we never tried `mergedGrid` with 3D and there may be some bugs.

**Comment by tibuch** [comment] 2023-03-17 08:50
[example.zip](https://github.com/mobie/mobie-viewer-fiji/files/10999537/example.zip)

This should contain everything. Currently the broken `dataset.json` is active. 

Will try out `transformedGrid` in a second.

**Comment by tibuch** [comment] 2023-03-17 08:59
How do I use `transformedGrid`?

```json
{
  "description": "A 3D projection mix example dataset.",
  "is2D": false,
  "sources": {
    "E07_C01_FITC_05": {
      "image": {
        "imageData": {
          "ome.zarr": {
            "channel": 0,
            "relativePath": "../../zarr-files/Projection-Mix.zarr/E/7/0"
          }
        }
      }
    },
    "E08_C01_FITC_05": {
      "image": {
        "imageData": {
          "ome.zarr": {
            "channel": 0,
            "relativePath": "../../zarr-files/Projection-Mix.zarr/E/8/0"
          }
        }
      }
    }
  },
  "views": {
    "default": {
      "isExclusive": true,
      "sourceDisplays": [
        {
          "imageDisplay": {
            "color": "r=115,g=255,b=0,a=255",
            "contrastLimits": [
              111,
              8065
            ],
            "name": "Plate-Channel-01",
            "opacity": 1.0,
            "sources": [
              "plate-channel-01-view"
            ]
          }
        }
      ],
      "sourceTransforms": [
        {
          "transformedGrid": {
            "name": "plate-channel-01-view",
            "positions": [
              [
                6,
                4
              ],
              [
                7,
                4
              ]
            ],
            "nestedSources": [
              ["E07_C01_FITC_05"],
              ["E08_C01_FITC_05"]
            ]
          }
        }
      ],
      "uiSelectionGroup": "bookmarks"
    }
  }
}
```

This is not liked by the validator:
`ValueError: Found wrong sources ['plate-channel-01-view'] in sourceDisplay: Plate-Channel-01`

**Comment by tischi** [comment] 2023-03-17 11:08
I think this:

```
 "sources": [
              "plate-channel-01-view"
            ]
```

now has to be:


```
 "sources": [
              "E07_C01_FITC_05",
               "E08_C01_FITC_05"
            ]
```

and you may have to remove this: ` "name": "plate-channel-01-view",`

Conceptually the difference is that `transformedGrid` does _not_ create a new source, it just moves sources around.

**Comment by tibuch** [comment] 2023-03-17 12:13
This works. But it creates for each well a `view` (? not sure if this is the correct term ?).
For each well I get now a green indicator:
![image](https://user-images.githubusercontent.com/5450869/225901062-838010c2-b6b7-40fd-8e45-be9e98922450.png)

Which gets slow with many hundreds of wells. Does that make sense to you?

**Comment by tischi** [comment] 2023-03-17 12:23
`view`: a drop-down item in the MoBIE UI that you can show
`green indicator`: a BDV source

I think this makes sense.
Because it does get slow this way we implemented the `mergedGrid` that stitches the hundreds of sources of a plate into one source.

Can you share some minimal example with me? Then I can debug / further develop the `mergedGrid` for 3D sources.

**Comment by tibuch** [comment] 2023-03-17 12:25
> [example.zip](https://github.com/mobie/mobie-viewer-fiji/files/10999537/example.zip)
> 
> This should contain everything. Currently the broken `dataset.json` is active.
> 
> Will try out `transformedGrid` in a second.

@tischi this zip should contain a minimal zarr-file and the mobie-project.

**Comment by tischi** [comment] 2023-03-17 12:36
is this a 3-D image?

`"../../zarr-files/Projection-Mix.zarr/E/7/0"`

**Comment by tibuch** [comment] 2023-03-17 12:39
`../../zarr-files/Projection-Mix.zarr/E/7/0/0` would be a 4D image (CZYX). 

The additional 0 indicates the zeroth resolution level.

**Comment by tischi** [comment] 2023-03-17 12:40
how many z-planes should it have?

**Comment by tibuch** [comment] 2023-03-17 12:42
`../../zarr-files/Projection-Mix.zarr/E/7/0/0/.zarray`: 
```
"shape": [
        4,
        10,
        512,
        1024
    ]
```

**Comment by tischi** [comment] 2023-03-17 12:53
Maybe this was an easy bug....

Does that look correct?

<img width="301" alt="image" src="https://user-images.githubusercontent.com/2157566/225909609-cfc5485c-d8de-44ed-ab43-9de3c5c4bba9.png">

Question: do you all your sources have the same number of z-planes?

**Comment by tibuch** [comment] 2023-03-17 12:54
Looks reasonable :slightly_smiling_face: 
And yes, all sources have the same number of z-planes.

**Comment by tischi** [comment] 2023-03-17 13:04
do you anticipate a use-case where this is not the case? 
if so I can probably handle it but it would be a bit more work. 
you could create an issue such that we do not forget :-)


this should work now:
- on `develop` branch
- on MoBIE-beta

**Comment by tibuch** [comment] 2023-03-17 13:08
I guess it would be possible to acquire such data. But for the foreseeable future I would not expect such a dataset to cross my desk. 

(Now that I have said it, it will probably happen on Monday :sweat_smile:)

I will test it on MoBIE-beta and create the issue. Thanks a lot!

**Comment by tischi** [comment] 2023-03-17 13:12
One more thing: do you have multiple wells with multiple fields?

**Comment by tibuch** [comment] 2023-03-17 13:14
Currently, we stitch the images during zarr-creation and store them as a single field.

**Comment by tibuch** [comment] 2023-03-17 13:17
Works on the small example. Will try it later on the big 384 plate.

**Comment by tischi** [comment] 2023-03-17 13:18
For MoBIE, you would not have to do this. 
You can do grids of grids (you can checkout the dataset.json of the covid-if repo).

One important trick: `"mergedGrid"` has a field: `"metadataSource"` 
If all your images have the same shape, you should just pick one image and put its name there all the time.
This can significantly speed up the initialisation, because then we only need to open one image to lazily initialise all the others.

However, in your current use-case you only have one "mergedGrid"?

**Comment by tischi** [comment] 2023-03-17 13:26
> Currently there is only one mergedGrid in our use-case.

Then I _think_ it does not matter whether you specify a "metadataSource" because it will just default to pick the first source (tile). I think this mainly helps for many wells, because then we can init all wells with the same metadata.

For fun here is the Java code:

```Java
				if ( mergedGridTransformation.metadataSource != null )
				{
					if ( dataSource.getName().equals( mergedGridTransformation.metadataSource ) )
						dataSource.preInit( true );
					else
						dataSource.preInit( false );
				}
				else // no metadata source specified, use the first in the grid as metadata source
				{
					final String firstImageInGrid = mergedGridTransformation.getSources().get( 0 );
					if ( dataSource.getName().equals( firstImageInGrid ) )
						dataSource.preInit( true );
					else
						dataSource.preInit( false );
				}
```

**Comment by tibuch** [comment] 2023-03-17 16:54
It also works on my big 384 well-plate :smiley: 

Thanks and have a nice weekend!

**Closed** 2023-03-17 18:46 UTC
