### ISSUE TITLE
Various issues and discussions

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#237] opened 2021-04-20 15:44 UTC
Hi,

when I right-click in the BDV-PG source list I get:

```
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: org/mastodon/app/ui/settings/SettingsPage
	at sc.fiji.bdvpg.scijava.services.ui.SourceAndConverterPopupMenu.<init>(SourceAndConverterPopupMenu.java:87)
	at sc.fiji.bdvpg.scijava.services.ui.SourceAndConverterPopupMenu.<init>(SourceAndConverterPopupMenu.java:122)
	at sc.fiji.bdvpg.scijava.services.ui.SourceAndConverterServiceUI$1.mouseClicked(SourceAndConverterServiceUI.java:178)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.Component.processMouseEvent(Component.java:6542)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: org.mastodon.app.ui.settings.SettingsPage
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 35 more
```

**Comment by tischi** [comment] 2021-04-20 16:04
@NicoKiaru I guess that means we have to ship also the mastodon jar?

**Comment by tischi** [comment] 2021-04-20 20:17
I uploaded bdv-selector (which I did not yet) and several mastodon jars

```
[INFO] Successfully uploaded to jars/mastodon-collection-1.0.0-beta-18.jar-20210420221544
[INFO] Successfully uploaded to jars/bigdataviewer-selector-0.1.8.jar-20210420221544
[INFO] Successfully uploaded to jars/mastodon-1.0.0-beta-16.jar-20210420221544
[INFO] Successfully uploaded to jars/mastodon-graph-1.0.0-beta-17.jar-20210420221544
```

@martinschorb Does that help?

**Comment by martinschorb** [comment] 2021-04-21 07:23
Seems to work now.
I got one full freeze but could not reproduce it.

Is it intentional that the BDV-PG sources list only shows up when adding a segmentation source? With multiple image sources, there's no sources list shown yet.

**Comment by NicoKiaru** [comment] 2021-04-21 07:52
Hi, yes some mastodon dependencies need to be updloaded - the ones you mentioned.

> Is it intentional that the BDV-PG sources list only shows up when adding a segmentation source? With multiple image sources, there's no sources list shown yet.

Do you mean the tree view ? What should be the intended behaviour for you ? You have a `Show Bdv Playground Window` command if that's useful for you. Normally the window should be updated automatically when you add new sources.

**Comment by tischi** [comment] 2021-04-21 08:23
Same question for me: would you like to see the Source Tree in MoBIE by default? I am reluctant because the screen becomes very full.

**Comment by martinschorb** [comment] 2021-04-21 08:24
OK, I am just not sure how MoBIE and the rest of the BDV (PG) window(s) intreract.

When I start MoBIE, I get 
- the MoBIE main window 
- a single BDV window (called MoBIE_00). This BDV window comes with the options tab (blue arrow).
- No TreeView (BDV-PG sources list, what is the official name...?)

The windows stay exactly the same, also when I add more image sources.

When I add a segmentation in MoBIE I get:

- additional source inside the BDV window
- segmentation label table window
- log window
- new BDV window (x-anchor,y-anchor) with the individual labels as point depicitions
- BDV sources tree view window

I just wonder why this all only shows up when adding a segmentation and not consistently from the beginning (or optional, maybe defined in some settings).

**Comment by tischi** [comment] 2021-04-21 08:27
- BDV source tree only during segmentation: That is a **bug**.
- Log window only during segmentation: That is a **bug**.
- Table and scatter plot only for segmentation: on purpose because they show the segment features.

**Comment by martinschorb** [comment] 2021-04-21 08:29
When I then close the MoBIE main window, all other windows stay. AFAIK there is no way getting it back in the current state, correct?

Also, the first click into the tree view (no matter whether in MoBIE-context or standalone) always triggers the Console window to open.

Maybe, something like a general " BDV window selector" - yet an additional window, yeah! Or you could maybe integrate it in the tree view below the sources (conceptionally this is where it should go in my view...) would be great to toggle individual windows on or off or bringing them to focus instead of having to deal with all of them individually.

**Comment by tischi** [comment] 2021-04-21 08:36
About the Source Tree: I would try to make it configurable (via right-click) whether it shows up and the default would be that it does not show up for MoBIE.

**Comment by martinschorb** [comment] 2021-04-21 08:36
Also the BDV-PG that ships with MoBIE-beta seems to be missing some libraries:
- start Fiji (MoBIE-beta)
- show BDV Playgorund window
- drag an xml source
- show source in new BDV window

```
[ERROR] Module threw error
java.lang.NoClassDefFoundError: bvv/util/BvvHandle
	at sc.fiji.bdvpg.scijava.processors.BvvHandlePostprocessor.lambda$process$1(BvvHandlePostprocessor.java:69)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at sc.fiji.bdvpg.scijava.processors.BvvHandlePostprocessor.process(BvvHandlePostprocessor.java:68)
	at org.scijava.module.ModuleRunner.postProcess(ModuleRunner.java:114)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:174)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: bvv.util.BvvHandle
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 12 more
```

**Comment by constantinpape** [comment] 2021-04-21 08:55
> About the Source Tree: I would try to make it configurable (via right-click) whether it shows up and the default would be that it does not show up for MoBIE.

I think this is a good solution. I would rather not have even more windows show up by default...

About all the different windows: at some point we discussed whether to disabling closing some of them independently (e.g. table or scatterplot) and for the rest whether to close everything if one window is closed (e.g. bdv window or mobie main menu). I still think this would be a good solution.

**Comment by NicoKiaru** [comment] 2021-04-21 10:41
> 
> 
> Also the BDV-PG that ships with MoBIE-beta seems to be missing some libraries:
> 
>     * start Fiji (MoBIE-beta)
> 
>     * show BDV Playgorund window
> 
>     * drag an xml source
> 
>     * show source in new BDV window
> 
> 
> ```
> [ERROR] Module threw error
> java.lang.NoClassDefFoundError: bvv/util/BvvHandle
> 	at sc.fiji.bdvpg.scijava.processors.BvvHandlePostprocessor.lambda$process$1(BvvHandlePostprocessor.java:69)
> 	at java.util.HashMap.forEach(HashMap.java:1289)
> 	at sc.fiji.bdvpg.scijava.processors.BvvHandlePostprocessor.process(BvvHandlePostprocessor.java:68)
> 	at org.scijava.module.ModuleRunner.postProcess(ModuleRunner.java:114)
> 	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:174)
> 	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
> 	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
> 	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.ClassNotFoundException: bvv.util.BvvHandle
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 12 more
> ```

Right, at the moment bigvolumeviewer-0.1.8-SNAPSHOT needs to be uplaoded. @tischi I can move the bvv stuff up to bdv-biop-tools to avoid that

**Comment by NicoKiaru** [comment] 2021-04-21 11:11
I thought there was an issue in Bdv-PG regarding the windows showing up or not, but I can't find it

**Comment by tischi** [comment] 2021-04-21 11:28
@NicoKiaru regarding BVV, is there a demo somewhere what one can do with it in the playground?

**Comment by NicoKiaru** [comment] 2021-04-21 11:31
> 
> 
> @NicoKiaru regarding BVV, is there a demo somewhere what one can do with it in the playground?

I don't think so. What do you prefer ? That I add one or that I remove the dependency ? FYI only 16-bits images are supported with BVV. You can create a BVV window and then show sources in it with the Fiji menu bar, but there'e no programmatic demo.

**Comment by tischi** [comment] 2021-04-21 11:38
I am actually thinking about use cases for MoBIE and the playground. If we could add a context menu item: `Show in BVV` which would show the SAC at the mouse position in BVV that could be very interesting. If that's possible then I would prefer to leave BVV in the playground.

**Comment by NicoKiaru** [comment] 2021-04-21 11:45
OK, let's keep it then. I still want to be able to link sciview from @skalarproduktraum and @kephale. Let's try to keep this in mind also

**Comment by tischi** [comment] 2021-04-21 11:57
Cool! And does the context menu item exist already or should I add it?

**Comment by NicoKiaru** [comment] 2021-04-21 12:01
The commands are in https://github.com/bigdataviewer/bigdataviewer-playground/tree/master/src/main/java/sc/fiji/bdvpg/scijava/command/bvv , and are already `BdvPlaygroundAction`s. Do we need something else ?

If we're going to use different viewer (BDV, BVV, Sciview), we could also revive the idea of the display interface ( but not now... let's try to have a plan for the "layer" stuff first).

**Comment by NicoKiaru** [comment] 2021-04-21 12:01
And bvv actions are in https://github.com/bigdataviewer/bigdataviewer-playground/tree/master/src/main/java/sc/fiji/bdvpg/bvv

**Comment by tischi** [comment] 2021-04-21 12:05
That sounds great! I would then try to add a simple `showInBVV` context menu when I find the time.

**Comment by constantinpape** [comment] 2021-08-12 10:22
There's a lot to unpack in this issue. AFAICT the only relevant thing here is support for BigVolumeViewer; which should maybe be moved into a separate issue.

**Comment by constantinpape** [comment] 2021-08-12 18:22
Added a new issue for BVV support: https://github.com/mobie/mobie-viewer-fiji/issues/415
Closing this one.

**Closed by constantinpape** 2021-08-12 18:22 UTC
