### ISSUE TITLE
Temporary documentation images storage

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#109] opened 2020-07-03 07:58 UTC
![image](https://user-images.githubusercontent.com/2157566/86445219-4ac97880-bd12-11ea-84a3-81436aec7beb.png)
![image](https://user-images.githubusercontent.com/2157566/86445323-79dfea00-bd12-11ea-8884-5e50a08660d0.png)
![image](https://user-images.githubusercontent.com/2157566/86445504-cdeace80-bd12-11ea-996a-4a6d5d58ccc7.png)
![image](https://user-images.githubusercontent.com/2157566/86445771-42be0880-bd13-11ea-9627-cd1ee7b62a99.png)

**Comment by constantinpape** [comment] 2021-03-01 19:16
@tischi I will close this as the links are valid regardless whether the issue is closed or not.
Just as a hint for the future: If you edit the README (or any other markdown file) in github online you can just drag and drop images in there and don't need to create issues for it.

**Closed by constantinpape** 2021-03-01 19:16 UTC
