### ISSUE TITLE
3D viewer origin with transformed sources

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#946] opened 2023-01-25 09:17 UTC
Hi,
I have transformed segmentations (3D CLEM both LM and EM, none is centered at the origin) that we like to visualize in the 3D viewer.

Can the origin of the 3D viewer be set to the center of the bounding box containing all visible objects instead of `0,0,0` ? 
The 3DViewer is barely usable otherwise (rotations are crazy).
![Screenshot from 2023-01-25 10-16-17](https://user-images.githubusercontent.com/35071867/214524567-88074415-9e63-4d41-af14-95b011b2f35a.png)

**Comment by tischi** [comment] 2023-01-26 09:44
@martinschorb you have to show me in person; let's mattermost chat to find a date.

**Comment by martinschorb** [comment] 2023-01-26 11:18
this happens with the segmentations in here:
https://github.com/mobie/environmental-dinoflagellate-vCLEM

**Comment by tischi** [comment] 2023-01-26 16:55
I feel the issue is that due to your coordinate system the mesh has negative coordinates.
It may be that the 3D viewer code has issue with this. 

I think the main issue right now for navigation is that it computes a totally wrong bounding box of the mesh.

Is there any way you could test this in a coordinate system, where your y-axis is shifted such that we have only positive coordinates?

<img width="307" alt="image" src="https://user-images.githubusercontent.com/2157566/214897859-d092d4f1-0e6b-42b7-8854-d497707fc273.png">

**Comment by tischi** [comment] 2023-01-26 17:08
Super weird:

The min and max of the mesh seem to be wrong:

<img width="580" alt="image" src="https://user-images.githubusercontent.com/2157566/214901519-83dbf73c-faa7-4359-922b-ef80de96f2ff.png">

But the bounds are correct:

<img width="678" alt="image" src="https://user-images.githubusercontent.com/2157566/214901728-43c1c95b-4486-4d21-9986-25a91df2ba5f.png">

I think this `1.4E-45` is the issue. No idea where that comes from...

**Comment by constantinpape** [comment] 2023-01-26 17:10
Did you check the corresponding table? Maybe this was some issue related to the empty objects. If you tell me which of the segmentations causes these issues I can also check.

**Comment by tischi** [comment] 2023-01-26 17:20
I found the bug. It is within the ImageJ 3D Universe code:

```
	public void calculateMinMaxCenterPoint(final Point3f min, final Point3f max,
		final Point3f center)
	{

		if (mesh == null || mesh.size() == 0) {
			min.set(0, 0, 0);
			max.set(0, 0, 0);
			center.set(0, 0, 0);
			return;
		}

		min.x = min.y = min.z = Float.MAX_VALUE;
		max.x = max.y = max.z = Float.MIN_VALUE; // <= WRONG, correct would be:   -Float.MAX_VALUE
		for (int i = 0; i < mesh.size(); i++) {
			final Point3f p = mesh.get(i);
			if (p.x < min.x) min.x = p.x;
			if (p.y < min.y) min.y = p.y;
			if (p.z < min.z) min.z = p.z;
			if (p.x > max.x) max.x = p.x;
			if (p.y > max.y) max.y = p.y;
			if (p.z > max.z) max.z = p.z;
		}
		center.x = (max.x + min.x) / 2;
		center.y = (max.y + min.y) / 2;
		center.z = (max.z + min.z) / 2;
	}
```

**Comment by tischi** [comment] 2023-01-29 11:29
I think I fixed it (follow the link above).

However, whether and when this fix will be shipped with Fiji is not clear.

I think there are three (non-exclusive) options:
1. You could move your coordinate system such that everything has positive coordinates
2. We ship our own version of 3D_Viewer
3. We wait until this is fixed in Fiji

**Closed** 2024-01-05 20:22 UTC
