### ISSUE TITLE
Error opening platybrowser

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#638] opened 2022-03-08 12:25 UTC
@KateMoreva (@constantinpape @K-Meech )

On the `develop` branch this throws me an error:

```
new MoBIE("https://github.com/platybrowser/platybrowser", MoBIESettings.settings().gitProjectBranch("main").imageDataFormat( ImageDataFormat.BdvN5S3 ) );
```

Could it be that there is a general bug for opening N5 data from S3 in mobie-io?

**Comment by constantinpape** [comment] 2022-03-08 12:26
Yes, it looks like this is currently broken, see this issue and also
https://github.com/mobie/mobie-io/issues/83
https://github.com/mobie/mobie-viewer-fiji/issues/636

**Comment by constantinpape** [comment] 2022-03-10 09:26
Hey @tischi @K-Meech,
is this issue also fixed now?

**Comment by K-Meech** [comment] 2022-03-10 09:35
This works now for me

**Comment by constantinpape** [comment] 2022-03-10 10:50
I can confirm that it works with the new MoBIE-beta, so closing this :).

**Closed by constantinpape** 2022-03-10 10:50 UTC
